package com.example.roomexample;

// Step 3: create Database class

import android.content.Context;

import androidx.room.Room;
import androidx.room.RoomDatabase;

/** Abstract class that extends "RoomDatabase".
 * Contains the database holder
 * annotated with @Database
 * Contain abstract method to retrieve the Data Access Object implementations created earlier
 * (these methods will be implemented by the subclass generated by Room)
 */
@androidx.room.Database(entities = User.class, version = 1) // describe which Entity is in a Database
public abstract class Database extends RoomDatabase {
    public abstract UserDao userDao();  // implemented by Room
    private static Database instance;

    public static Database getInstance(Context context){
        if(instance == null){   // use only single instance (singleton)
            instance = Room.databaseBuilder(context, Database.class, "MyDB")
                    .allowMainThreadQueries()
                    .build();
        }
        return instance;
    }
}
